services:
  - type: web
    name: riddhibanerjee-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    region: oregon
    healthCheckPath: /api/profile
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_H2_CONSOLE_ENABLED
        value: false
