spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:portfoliodb}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:postgres}}
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
